title: Ravencoin
description: A peer-to-peer blockchain built to move assets.
baseurl: ""  # Important for root domain
url: "https://notadeveloper-97.github.io"
markdown: kramdown
theme: minima  # or your custom theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# For better mobile
sass:
  sass_dir: _sass